Feature/new landing page
Fabi911/Capstone_Plant_Care pull request #34
Opened 2024-04-10 10:45 UTC by HenrikBischkopf

2024-04-10 14:06 UTC, JessicaLoers requested changes
Please pay attention to the use of the react fragments.

2024-04-10 14:06 UTC, JessicaLoers commented on pages/watering.js
> +  }
Consider to use a functional update for the state to ensure the latest state value is always used -  safety first 👮

```suggestion
function handleNextDay() {
    setDay((currentDay) => currentDay + 1); 
      }
```

2024-04-10 14:06 UTC, JessicaLoers commented on pages/watering.js
> +  ];
Consider to move this outside your component. Although the performance gain might be negligible in this specific case, moving static data outside of a component prevents it from being recreated on every render.

2024-04-10 20:17 UTC, Fabi911 commented on components/Tile.js
> +    Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
that's not final.

2024-04-11 06:56 UTC, JessicaLoers approved these changes
**Well done ✨**

2024-04-11 06:56 UTC, JessicaLoers commented on components/FertilizingSchedule.js
> +              {(fertilizedSeasons = plant.fertiliser_season.join(", "))}
nice 👍

2024-04-11 06:56 UTC, JessicaLoers commented on pages/404.js
> +  return <h1>Shit happens 💩</h1>;
Super important change.

2024-04-11 07:40 UTC, merged